### ISSUE TITLE
Secure Boot Enabled Install Environment

### ISSUE THREAD

**Issue by BeardedTek** [nix-community/lanzaboote#284] opened 2024-01-17 03:37 UTC
I've created a secure boot enabled installer using Lanzaboote with the current unstable NixOS (24.05).  It functions and was able to install on my workstation with secure boot enabled.

https://github.com/BeardedTek/nixos-24.05-secureboot-installer/releases/tag/2024-01-16-001

I have a writeup on my blog:
https://beardedtek.org/my-nixos-journey-pt-4/

This was all done on a whim for fun and I'm sure I'm missing tons of technical details and could optimize it much further, but figured y'all might want to take a peek.

**Comment by nikstur** [comment] 2024-06-09 23:23
Really cool! Thanks for linking this here.

However, I'll close this issue so we can keep track of actionable issues.

People should still be able to find this even if the issue is closed.

**Closed by nikstur** 2024-06-09 23:23 UTC
