### ISSUE TITLE
EFI Files were not actually signed 

### ISSUE THREAD

**Issue by C0D3-M4513R** [nix-community/lanzaboote#252] opened 2023-11-03 06:17 UTC
```console
[user@nixos:~/nixos-config]$ sudo nixos-rebuild test --flake .#nixos-laptop
warning: Git tree '/home/user/nixos-config' is dirty
building the system configuration...
warning: Git tree '/home/user/nixos-config' is dirty
stopping the following units: accounts-daemon.service
NOT restarting the following changed units: systemd-fsck@dev-disk-by\x2duuid-EC9B\x2d26DD.service, systemd-fsck@dev-disk-by\x2duuid-c4f75be6\x2db5a0\x2d4832\x2da96a\x2df1097b1528ce.service
activating the configuration...
setting up /etc...
reloading user units for user...
setting up tmpfiles
reloading the following units: dbus.service
restarting the following units: polkit.service
starting the following units: accounts-daemon.service
```

<details><summary>secure-boot.nix</summary>
<p>

```nix
#all according to: https://nixos.wiki/wiki/Secure_Boot and https://github.com/nix-community/lanzaboote/blob/master/docs/QUICK_START.md
{lib,pkgs,...}:
{

  environment.systemPackages = [
    # For debugging and troubleshooting Secure Boot.
    pkgs.sbctl
  ];

  boot = {
   bootspec.enable = true;
   loader.systemd-boot.enable = lib.mkForce false;
   loader.grub.enable = lib.mkForce false; 
   lanzaboote = {
      enable = true;
      pkiBundle = "/etc/secureboot";
    };
  };

}

```

</p></details>

<details><summary>flake.nix</summary>
<p>

```nix
{
  description = "System Nixos Flake";

  inputs = {
    # There are many ways to reference flake inputs.
    # The most widely used is `github:owner/name/reference`,
    # which represents the GitHub repository URL + branch/commit-id/tag.

    # Official NixOS package source, using nixos-unstable branch here
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.05";
    unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
    lanzaboote = {
      url = "github:nix-community/lanzaboote";
      inputs.nixpkgs.follows = "unstable";
    };
    sops-nix = {
      url = "github:Mic92/sops-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    # home-manager, used for managing user configuration
    #home-manager = {
    #  url = "github:nix-community/home-manager/release-23.05";
    #  # The `follows` keyword in inputs is used for inheritance.
    #  # Here, `inputs.nixpkgs` of home-manager is kept consistent with
    #  # the `inputs.nixpkgs` of the current flake,
    #  # to avoid problems caused by different versions of nixpkgs.
    #  inputs.nixpkgs.follows = "nixpkgs";
    #};
  };
  outputs = { self, nixpkgs, unstable, lanzaboote, sops-nix, ... }:
  let
    upkgs = { pkgs, ... }: {
          _module.args.upkgs = import unstable { 
            inherit (pkgs.stdenv.targetPlatform) system;
            config.allowUnfree = true; 
          };
    };
    in {

      nixosConfigurations = {
        "nixos-pc" = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          specialArgs.channels = { inherit nixpkgs unstable; };
          modules =  [
            upkgs
            ./hardware-configuration.nix
            ./configuration.nix
            ./fde.nix
#            lanzaboote.nixosModules.lanzaboote
#            ./secure-boot.nix
#            lenovo_ideapad_pro_5_16ach6/specific.nix
#            ./battery_power.nix
            ./localisazion.nix
            ./io.nix
            io/disks.nix
            io/graphical.nix
            io/networking.nix
            io/sound.nix
            ./latex.nix
            ./virtualization.nix
            ./gaming.nix
            ./amdgpu.nix
            ./netdata.nix
            sops-nix.nixosModules.sops
            ];
#redacted some fs mounts


#            sops.defaultSopsFile = ./secrets.yaml;
#            sops.defaultSopsFormat = "yml";
#            sops.secrets.initrd = {
#              keyfile0 = {
#                format="binary";
#                sopsFile="secrets/initrd/keyfile0.bin";
#              };
#              keyfile1 = {
#                format="binary";
#                sopsFile="secrets/initrd/keyfile1.bin";
#              };
#            };
        };
        "nixos-laptop" = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          specialArgs.channels = { inherit nixpkgs unstable; };
          modules =  [
            upkgs
            ./hardware-configuration.nix
            ./configuration.nix
            ./fde.nix
            lanzaboote.nixosModules.lanzaboote
            ./secure-boot.nix
            lenovo_ideapad_pro_5_16ach6/specific.nix
            ./battery_power.nix
            ./localisazion.nix
            ./io.nix
            io/disks.nix
            io/graphical.nix
            io/networking.nix
            io/sound.nix
            ./latex.nix
#            ./virtualization.nix
            ./gaming.nix
#            ./amdgpu.nix
#            ./netdata.nix
#            sops-nix.nixosModules.sops
            ];
#            sops.defaultSopsFile = ./secrets.yaml;
#            sops.defaultSopsFormat = "yml";
#            sops.secrets.initrd = {
#              keyfile0 = {
#                format="binary";
#                sopsFile="secrets/initrd/keyfile0.bin";
#              };
#              keyfile1 = {
#                format="binary";
#                sopsFile="secrets/initrd/keyfile1.bin";
#              };
#            };
        };
      };
    };
}
```
</p>
</details>

```console
[user@nixos:~/nixos-config]$ sudo nix run nixpkgs#sbctl verify
Verifying file database and EFI images in /boot/efi...
✗ /boot/efi/EFI/Boot/KeyTool.efi is not signed
✗ /boot/efi/EFI/Boot/bootx64.efi is not signed
✗ /boot/efi/EFI/Boot/bootx64.efi.old is not signed
✗ /boot/efi/EFI/Boot/grubx64.efi is not signed
✗ /boot/efi/EFI/Boot/mmx64.efi is not signed
✗ /boot/efi/EFI/Boot/shimx64.efi is not signed
✗ /boot/efi/EFI/NixOS-boot-efi/grubx64.efi is not signed
```

**Comment by RaitoBezarius** [comment] 2023-11-03 12:27
Well, it's not supposed to sign something else than systemd-boot and the lanzaboote stub. You have potentially a mountpoint confusion issue with your ESP. I only see GRUB, shim and the key tooling. It seems to be related to your setup.

Closing as I fear this is not actionable / reproducible on our side, feel free to comment again if you feel like we should reopen this.

**Closed by RaitoBezarius** 2023-11-03 12:27 UTC
