### ISSUE TITLE
Lanzaboote is failing to builld

### ISSUE THREAD

**Issue by arthsmn** [nix-community/lanzaboote#345] opened 2024-05-30 20:46 UTC
I updated my system flake today and lanzaboote is not compiling. I tried cleaning my nix store and downloading everything again but the same happened.

The log:
``` log
cargoArtifacts not set, will not reuse any cargo artifacts
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/frn377xg05r9gl0d77bcxh44lkzsg55i-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
Executing configureCargoCommonVars
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
will append /build/source/.cargo-home/config.toml with contents of /nix/store/8ll25yc1449wsvis0rsxh9ldvw74h93h-vendor-cargo-deps/config.toml
default configurePhase, nothing to do
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
++ command cargo --version
cargo 1.68.2 (6feb7c9cf 2023-03-26)
++ command cargo check --release
warning: unused manifest key: package.rust_version
  Compiling proc-macro2 v1.0.56
  Compiling quote v1.0.26
  Compiling unicode-ident v1.0.8
  Compiling syn v1.0.109
  Compiling typenum v1.16.0
  Compiling version_check v0.9.4
   Checking cfg-if v1.0.0
  Compiling log v0.4.17
   Checking bit_field v0.10.2
   Checking bitflags v1.3.2
   Checking plain v0.2.3
  Compiling lanzaboote_stub v0.1.0 (/build/source)
   Checking cpufeatures v0.2.6
   Checking ucs2 v0.3.2
  Compiling generic-array v0.14.7
   Checking block-buffer v0.10.4
   Checking crypto-common v0.1.6
   Checking digest v0.10.6
   Checking sha2 v0.10.6
  Compiling ptr_meta_derive v0.2.0
  Compiling scroll_derive v0.11.0
  Compiling uefi-macros v0.11.0
   Checking ptr_meta v0.2.0
   Checking uefi v0.20.0
   Checking scroll v0.11.0
   Checking goblin v0.6.1
   Checking uefi-services v0.17.0
   Finished release [optimized] target(s) in 5.03s
++ command cargo build --release
warning: unused manifest key: package.rust_version
  Compiling cfg-if v1.0.0
  Compiling typenum v1.16.0
  Compiling bit_field v0.10.2
  Compiling bitflags v1.3.2
  Compiling plain v0.2.3
  Compiling cpufeatures v0.2.6
  Compiling ptr_meta v0.2.0
  Compiling scroll v0.11.0
  Compiling log v0.4.17
  Compiling ucs2 v0.3.2
  Compiling uefi v0.20.0
  Compiling goblin v0.6.1
  Compiling generic-array v0.14.7
  Compiling block-buffer v0.10.4
  Compiling crypto-common v0.1.6
  Compiling digest v0.10.6
  Compiling sha2 v0.10.6
  Compiling uefi-services v0.17.0
  Compiling lanzaboote_stub v0.1.0 (/build/source)
error: linking with `rust-lld` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/nix/store/csz8q3x3pxakpmmrs9h3kcaz70wp1dp1-rust-default-1.68.2/lib/rustlib/x86_64-unknown-linux-gnu/bin:/nix/store/9bv7dcvmfcjnmg5mnqwqlq2wxfn8d7yi-gcc-wrapper-13.2.0/bin:/nix/store/14c6s4xzhy14i2b05s00rjns2j93gzz4-gcc-13.2.0/bin:/nix/store/c2i631h8i5vcs1sqifwxfsazhwrg6wr5-glibc-2.39-52-bin/bin:/nix/store/php4qidg2bxzmm79vpri025bqi0fa889-coreutils-9.5/bin:/nix/store/kln7kinji3b7sz8r50h4gn9yy6k1js9a-binutils-wrapper-2.41/bin:/nix/store/bgcaxhhxswzvmxjbbgvvaximm5hwghz1-binutils-2.41/bin:/nix/store/csz8q3x3pxakpmmrs9h3kcaz70wp1dp1-rust-default-1.68.2/bin:/nix/store/hxhdhc0zddbhmqvv99nldq2gfmy9983x-zstd-1.5.6-bin/bin:/nix/store/by853zqacqy647v0z7l70xm77xl9ifal-zstd-1.5.6/bin:/nix/store/nbad47q0m0m9c5xid7zh05hiknwircbp-patchelf-0.15.0/bin:/nix/store/php4qidg2bxzmm79vpri025bqi0fa889-coreutils-9.5/bin:/nix/store/jjcsr5gs4qanf7ln5c6wgcq4sn75a978-findutils-4.9.0/bin:/nix/store/i34mknsjgrfyy71k2h79gda0bvagzc2j-diffutils-3.10/bin:/nix/store/5zjms21vpxlkbc0qyl5pmj2sidfmzmd7-gnused-4.9/bin:/nix/store/28gpmx3z6ss3znd7fhmrzmvk3x5lnfbk-gnugrep-3.11/bin:/nix/store/8vvkbgmnin1x2jkp7wcb2zg1p0vc4ks9-gawk-5.2.2/bin:/nix/store/rik7p68cq7yzlj5pmfpf4yv6jnrpvlgf-gnutar-1.35/bin:/nix/store/j5chw7v1x3vlmf3wmdpdb5gwh9hl0b80-gzip-1.13/bin:/nix/store/mxcq77rlan82dzpv3cgj0fh6qvv8ncil-bzip2-1.0.8-bin/bin:/nix/store/cdzpn0rdq810aknww3w9fy3wmw9ixr66-gnumake-4.4.1/bin:/nix/store/306znyj77fv49kwnkpxmb0j2znqpa8bj-bash-5.2p26/bin:/nix/store/0lfxbmchigx9vs9qmrlbahcy6nxwfnj1-patch-2.7.6/bin:/nix/store/6i4xxaa812vsbli9jkq4mksdddrk27lw-xz-5.4.6-bin/bin:/nix/store/xx7x1dwybpssfhq8yikvzz38bh3yrq97-file-5.45/bin" VSLANG="1033" "rust-lld" "-flavor" "link" "/NOLOGO" "/entry:efi_main" "/subsystem:efi_application" "/build/rustcM4D7st/symbols.o" "/build/source/target/x86_64-unknown-uefi/release/deps/crane_dummy-5a93b6591151f4cb.crane_dummy.2483549a-cgu.0.rcgu.o" "/LIBPATH:/build/source/target/x86_64-unknown-uefi/release/deps" "/LIBPATH:/build/source/target/release/deps" "/LIBPATH:/nix/store/csz8q3x3pxakpmmrs9h3kcaz70wp1dp1-rust-default-1.68.2/lib/rustlib/x86_64-unknown-uefi/lib" "/nix/store/620wbknn2jr036n94j43zf1jrj4zaaqi-rust-std-1.68.2-x86_64-unknown-uefi/lib/rustlib/x86_64-unknown-uefi/lib/libcompiler_builtins-68429de2e476cc27.rlib" "/NXCOMPAT" "/LIBPATH:/nix/store/csz8q3x3pxakpmmrs9h3kcaz70wp1dp1-rust-default-1.68.2/lib/rustlib/x86_64-unknown-uefi/lib" "/OUT:/build/source/target/x86_64-unknown-uefi/release/deps/crane_dummy-5a93b6591151f4cb.efi" "/OPT:REF,ICF" "/DEBUG" "/NODEFAULTLIB"
  = note: .rust-lld-unwrapped: warning: ignoring unknown argument '-z'
          .rust-lld-unwrapped: warning: ignoring unknown argument '-z'
          .rust-lld-unwrapped: warning: ignoring unknown argument '-L/nix/store/csz8q3x3pxakpmmrs9h3kcaz70wp1dp1-rust-default-1.68.2/lib'
          .rust-lld-unwrapped: warning: ignoring unknown argument '-L/nix/store/by853zqacqy647v0z7l70xm77xl9ifal-zstd-1.5.6/lib'
          .rust-lld-unwrapped: warning: ignoring unknown argument '-L/nix/store/csz8q3x3pxakpmmrs9h3kcaz70wp1dp1-rust-default-1.68.2/lib'
          .rust-lld-unwrapped: warning: ignoring unknown argument '-L/nix/store/by853zqacqy647v0z7l70xm77xl9ifal-zstd-1.5.6/lib'
          .rust-lld-unwrapped: warning: ignoring unknown argument '-L/nix/store/csz8q3x3pxakpmmrs9h3kcaz70wp1dp1-rust-default-1.68.2/lib'
          .rust-lld-unwrapped: warning: ignoring unknown argument '-L/nix/store/by853zqacqy647v0z7l70xm77xl9ifal-zstd-1.5.6/lib'
          .rust-lld-unwrapped: warning: ignoring unknown argument '-rpath'
          .rust-lld-unwrapped: warning: ignoring unknown argument '-L/nix/store/csz8q3x3pxakpmmrs9h3kcaz70wp1dp1-rust-default-1.68.2/lib'
          .rust-lld-unwrapped: warning: ignoring unknown argument '-L/nix/store/by853zqacqy647v0z7l70xm77xl9ifal-zstd-1.5.6/lib'
          .rust-lld-unwrapped: warning: ignoring unknown argument '-L/nix/store/csz8q3x3pxakpmmrs9h3kcaz70wp1dp1-rust-default-1.68.2/lib'
          .rust-lld-unwrapped: warning: ignoring unknown argument '-L/nix/store/by853zqacqy647v0z7l70xm77xl9ifal-zstd-1.5.6/lib'
          .rust-lld-unwrapped: error: could not open 'relro': No such file or directory
          .rust-lld-unwrapped: error: could not open 'now': No such file or directory
          .rust-lld-unwrapped: error: could not open '/nix/store/sjnk45sspm63ljhjbwlwjkm2nk1ilhmr-lanzaboote_stub-deps-0.1.0/lib': No such file or directory
          

error: could not compile `lanzaboote_stub` due to previous error

```

**Comment by oxalica** [comment] 2024-05-31 00:12
It's caused by https://github.com/oxalica/rust-overlay/issues/173, and should be fixed by updating rust-overlay.

**Closed** 2024-05-31 00:31 UTC
